/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/popup_book.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.ceil_01.geometry} material={materials.sheet_ceil} position={[0, 3.34, 0]} />
      <mesh geometry={nodes.floor_01.geometry} material={materials.sheet_floor} position={[-3.31, 0.01, 0]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.back_01.geometry} material={materials.content_back} position={[-0.27, 4.61, 0]} scale={[1, 0.67, 1.09]} />
      <mesh geometry={nodes.front_01.geometry} material={materials.content_front} position={[-4.28, 2.05, 0]} scale={[1, 0.61, 1]} />
      <mesh geometry={nodes.main_01.geometry} material={materials.content_main} position={[-1.98, 2.05, 0]} scale={[1, 0.61, 1]} />
      <mesh geometry={nodes.ceil_02.geometry} material={materials.sheet_ceil_02} position={[0, 3.34, 0]} />
      <mesh geometry={nodes.ceil_stripetent.geometry} material={materials.ceil_stripetent} position={[-0.98, 6.25, 0]} rotation={[0, 0, -1.15]} scale={[1, 0.31, 1]} />
      <mesh geometry={nodes.ceil_stripetent_tail.geometry} material={materials.ceil_stripetent_tail} position={[-1.94, 5.49, 0]} scale={[1, 0.1, 1]} />
      <mesh geometry={nodes.floor_02.geometry} material={materials.sheet_floor_02} position={[-3.31, 0.01, 0]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.front_02.geometry} material={materials.content_front} position={[-4.28, 2.05, 0]} scale={[1, 0.61, 1]} />
      <mesh geometry={nodes.main_02.geometry} material={materials.content_main} position={[-1.98, 2.05, 0]} scale={[1, 0.61, 1]} />
      <mesh geometry={nodes.ceil_03.geometry} material={materials.sheet_ceil_03} position={[0, 3.34, 0]} />
      <mesh geometry={nodes.floor_03.geometry} material={materials.sheet_floor_03} position={[-3.31, 0.01, 0]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.front_03.geometry} material={materials.content_front} position={[-4.28, 2.05, 0]} scale={[1, 0.61, 1]} />
      <mesh geometry={nodes.main_03.geometry} material={materials.content_main} position={[-1.98, 2.05, 0]} scale={[1, 0.61, 1]} />
      <mesh geometry={nodes.ceil_04.geometry} material={materials.sheet_ceil_04} position={[0, 3.34, 0]} />
      <mesh geometry={nodes.floor_04.geometry} material={materials.sheet_floor_04} position={[-3.31, 0.01, 0]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.back_04.geometry} material={materials.content_back} position={[-0.27, 4.61, 0]} scale={[1, 0.67, 1.09]} />
      <mesh geometry={nodes.front_04.geometry} material={materials.content_front} position={[-4.28, 2.05, 0]} scale={[1, 0.61, 1]} />
      <mesh geometry={nodes.main_04.geometry} material={materials.content_main} position={[-1.98, 2.05, 0]} scale={[1, 0.61, 1]} />
    </group>
  )
}

useGLTF.preload('/popup_book.glb')
